# Generated by Django 4.1.3 on 2022-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasionuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
