# Generated by Django 4.1.3 on 2022-12-15 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_firmprofile_firm_name_alter_firmprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmprofile',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^[+|0|00]\\d{7,13}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^[+|0|00]\\d{7,13}$')]),
        ),
    ]
