# Generated by Django 4.1.3 on 2022-12-15 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_firmprofile_phone_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Area is not in correct format', regex='^[+|0|00]\\d{7,13}$')]),
        ),
    ]
