# Generated by Django 4.1.3 on 2022-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_firmprofile_phone_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmprofile',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
