# Generated by Django 4.1.3 on 2022-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_firmprofile_phone_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasionuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
