# Generated by Django 4.1.3 on 2022-11-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_occasionuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occasionuser',
            name='last_name',
        ),
    ]
