# Generated by Django 4.1.3 on 2022-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_occasionuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasionuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
