# Generated by Django 4.1.3 on 2022-12-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline')], max_length=8)),
                ('category', models.CharField(blank=True, choices=[('Box', 'Box'), ('Car carrier', 'Car carrier'), ('Dumper truck', 'Dumper truck'), ('Food Carrier', 'Food Carrier'), ('Grain Truck', 'Grain Truck'), ('Mining Truck', 'Mining Truck'), ('Hydraulic Platform', 'Hydraulic Platform'), ('Over truck over 7.5 t', 'Over truck over 7.5 t')], max_length=21, null=True)),
                ('first_reg_date', models.DateField()),
                ('price', models.CharField(max_length=15)),
                ('kilometers', models.CharField(max_length=15)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=9)),
                ('photo', models.URLField()),
                ('photo2', models.URLField(blank=True, null=True)),
                ('photo3', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('type', models.CharField(blank=True, choices=[('Naked Bike', 'Naked Bike'), ('Scooter', 'Scooter'), ('Chopper', 'Chopper'), ('Motorcycle', 'Motorcycle'), ('Enduro', 'Enduro')], max_length=10, null=True)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Other', 'Other')], max_length=8)),
                ('price', models.CharField(max_length=15)),
                ('first_reg_date', models.DateField()),
                ('kilometers', models.CharField(max_length=15)),
                ('photo', models.URLField()),
                ('photo2', models.URLField(blank=True, null=True)),
                ('photo3', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('body_style', models.CharField(blank=True, choices=[('Cargo van', 'Cargo van'), ('Combi', 'Combi'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Wagon', 'Wagon')], max_length=9, null=True)),
                ('km', models.CharField(max_length=15)),
                ('first_reg_date', models.DateField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=9)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=8)),
                ('color', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=15)),
                ('photo', models.URLField()),
                ('photo2', models.URLField(blank=True, null=True)),
                ('photo3', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
