# Generated by Django 4.1.3 on 2022-11-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='description',
            new_name='body_style',
        ),
    ]
