# Generated by Django 4.1.3 on 2022-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_car_body_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carphoto',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='carphoto',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
