# Generated by Django 4.1.3 on 2022-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_carphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo2',
            field=models.URLField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='photo3',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
