# Generated by Django 4.1.3 on 2022-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_carphoto_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.FloatField(),
        ),
    ]
