# Generated by Django 4.1.3 on 2022-12-13 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorbike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('type', models.CharField(blank=True, choices=[('Naked Bike', 'Naked Bike'), ('Scooter', 'Scooter'), ('Chopper', 'Chopper'), ('Motorcycle', 'Motorcycle'), ('Enduro', 'Enduro')], max_length=10, null=True)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Other', 'Other')], max_length=8)),
                ('price', models.CharField(max_length=15)),
                ('first_reg_date', models.DateField()),
                ('kilometers', models.CharField(max_length=15)),
                ('photo', models.URLField()),
                ('photo2', models.URLField(blank=True, null=True)),
                ('photo3', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
