# Generated by Django 4.1.3 on 2022-11-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
